service: ds-sqs-kafka-relay

# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1 #eu-west-1 use us-east-1 for better performance with CloudKarafka

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
  include:
    - certs/**
  exclude:
    - node_modules/**
    - requirements.txt

functions:
  hello:
    handler: handler.hello
    memorySize: 256
    timeout: 20
    events:
      - http:
          path: hello
          method: get
          cors: true
          authorizer:
            type: aws_iam


plugins:
  - serverless-python-requirements
